<?php

namespace AppBundle\Repository;

/**
 * ServerRamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRamRepository extends \Doctrine\ORM\EntityRepository
{
}
